In [25]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

raw_data = pd.read_csv('/content/vgames2.csv')
raw_data

#Data 전처리 시작(필요없는 columns제거, 결측치 처리, 출고량 숫자 단위)

raw_data= raw_data.drop(['Unnamed: 0'], axis=1) #불필요 column 제거
raw_data.isnull().sum() # Year  271, Genre 50, Publisher 58

raw_data= raw_data.dropna(0) 

raw_data.dtypes #Year=float64, All_Sales = object

raw_data.head()

#Year의 이상한 년도 제대로 바꿔야 함
#K , M해결하고 숫자형 데이터로 바꿔야 함 raw_data= raw_data.dropna(0) 

raw_data['Year'] = raw_data['Year'].apply(pd.to_numeric, errors = 'coerce').fillna(0)

y = raw_data['Year'] 
#print(y.value_counts())

year_change= list()
for i in y:
  if 0<i<20:
    year_change.append(i+2000)
  elif 20<i<100:
  	year_change.append(i+1900)
  else:
    year_change.append(i)

year_change= pd.DataFrame({'year': year_change})
new_year = year_change
new_year.reset_index(drop=True, inplace=True)
raw_data.reset_index(drop=True, inplace=True)

raw_data = pd.concat([raw_data, new_year], axis=1)
raw_data= raw_data.drop(['Year'], axis=1)
raw_data   #year 끝

#K , M해결하고 숫자형 데이터로 바꿔야 함 raw_data= raw_data.dropna(0) 
# NA_Sales, EU_Sales, JP_Sales , Other_Sales

#raw_data['NA_Sales'].isin({'NA_Sales': ['K', 'M']})
#raw_data['NA_Sales'].astype(str).contains('K')

raw_data['NA_Sales'] = raw_data['NA_Sales'].str.replace('K', '000')
raw_data['NA_Sales'] = raw_data['NA_Sales'].str.replace('M', '')

raw_data['EU_Sales'] = raw_data['EU_Sales'].str.replace('K', '000')
raw_data['EU_Sales'] = raw_data['EU_Sales'].str.replace('M', '')

raw_data['JP_Sales'] = raw_data['JP_Sales'].str.replace('K', '000')
raw_data['JP_Sales'] = raw_data['JP_Sales'].str.replace('M', '')

raw_data['Other_Sales'] = raw_data['Other_Sales'].str.replace('K', '000')
raw_data['Other_Sales'] = raw_data['Other_Sales'].str.replace('M', '')


raw_data['NA_Sales'] = raw_data['NA_Sales'].apply(pd.to_numeric, errors = 'coerce').fillna(0)  #N
raw_data['EU_Sales'] = raw_data['EU_Sales'].apply(pd.to_numeric, errors = 'coerce').fillna(0)  #E
raw_data['JP_Sales'] = raw_data['JP_Sales'].apply(pd.to_numeric, errors = 'coerce').fillna(0)  #J
raw_data['Other_Sales'] = raw_data['Other_Sales'].apply(pd.to_numeric, errors = 'coerce').fillna(0)  #O





##value_change(raw_data['NA_Sales'])
##raw_data['NA_Sales'][10]


raw_data['NA_Sales'].dtypes
N = raw_data['NA_Sales']
NA_change= list()
for i in N:
  if i<1000:
    NA_change.append(i*1000000)
  elif i>1000:
  	NA_change.append(i)
  else:
    NA_change.append(i)

NA_change

E= raw_data['EU_Sales']
EU_change= list()
for i in E:
  if i<1000:
    EU_change.append(i*1000000)
  elif i>1000:
  	EU_change.append(i)
  else:
    EU_change.append(i)

J = raw_data['JP_Sales']
JP_change= list()
for i in J:
  if i<1000:
    JP_change.append(i*1000000)
  elif i>1000:
  	JP_change.append(i)
  else:
    JP_change.append(i)

O = raw_data['Other_Sales']
Other_change= list()
for i in O:
  if i<1000:
    Other_change.append(i*1000000)
  elif i>1000:
  	Other_change.append(i)
  else:
    Other_change.append(i)

new_data= pd.DataFrame({'NA_Sales_n': NA_change,
                       'EU_Sales_n' :EU_change,
                       'JP_Sales_n' : JP_change,
                        'Other_Sales_n' :Other_change})

new_data
df = pd.concat([raw_data, new_data], axis=1)
df= df.drop(['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales'], axis=1)

#전처리 일단 끝
#필수 인사이트
# 1. 지역에 따라서 선호하는 게임 장르가 다를까 
# 2. 연도별 게임의 트렌드가 있을까
# 3. 출고량이 높은 게임에 대한 분석(플랫폼, 장르) 및 시각화 프로세스


#1-1 지역에 따라 선호하는 게임장르
sector_NA= df[['Genre', 'NA_Sales_n']]
sector_NA.sort_values(by=['Genre', 'NA_Sales_n'], ascending = [True, False])
grouped = sector_NA.groupby('Genre')
N=grouped.sum()['NA_Sales_n']  #Action          858750000.0
#N.plot.barh();



sector_EU= df[['Genre', 'EU_Sales_n']]
sector_EU.sort_values(by=['Genre', 'EU_Sales_n'], ascending = [True, False])
grouped = sector_EU.groupby('Genre')
E=grouped.sum()['EU_Sales_n']  #Action 513640000.
#E.plot.barh();

sector_JP= df[['Genre', 'JP_Sales_n']]
sector_JP.sort_values(by=['Genre', 'JP_Sales_n'], ascending = [True, False])
grouped = sector_JP.groupby('Genre')
J=grouped.sum()['JP_Sales_n']  #Role-Playing    342930000.0
#J.plot.barh();


sector_Ot= df[['Genre', 'Other_Sales_n']]
sector_Ot.sort_values(by=['Genre', 'Other_Sales_n'], ascending = [True, False])
grouped = sector_Ot.groupby('Genre')
O=grouped.sum()['Other_Sales_n']  #Action          183990000.0
#O.plot.barh();


#2-1 연도별 게임의 트렌드
#
df['All_Sales']= df['NA_Sales_n']+df['EU_Sales_n']+df['JP_Sales_n']+df['Other_Sales_n']
a= df.sort_values(by=['All_Sales'], axis=0, ascending = False) # Wii Sports	Wii	Sports	Nintendo 총 판매	82740000.0, 누적판매량 상위 5위 (Nintendo)